### ISSUE TITLE
undefined variable：currentLanguage 

### ISSUE THREAD

**Issue by asyncpjax** [mouyong/validate#3]
`default.ERROR: Undefined variable: currentLanguage [] []
[2022-11-08 14:49:16] default.ERROR: #0 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\mouyong\validate\src\ValidatorFactory.php(75): support\App::{closure}(8, 'Undefined varia...', 'D:\\phpstudy_pro...', 75, Array)
#1 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\mouyong\validate\src\ValidatorFactory.php(34): Mouyong\Validate\ValidatorFactory->loadTranslator()
#2 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\mouyong\validate\src\ValidatorFactory.php(83): Mouyong\Validate\ValidatorFactory->getFactory()
#3 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\mouyong\validate\src\helpers.php(22): Mouyong\Validate\ValidatorFactory->__call('make', Array)
#4 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\app\VerifyRequestInput.php(118): validator(Array, Array)
#5 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\app\inputs\Input.php(22): app\inputs\Input->check(Array, Array)
#6 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\app\inputs\Input.php(46): app\inputs\Input->fill(Array)
#7 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\app\api\controller\Index.php(23): app\inputs\Input::new()
#8 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\workerman\webman-framework\src\App.php(284): app\api\controller\Index->gameList(Object(support\Request))
#9 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\workerman\webman-framework\src\App.php(304): Webman\App::Webman\{closure}(Object(support\Request))
#10 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\webman\cors\src\CORS.php(12): Webman\App::Webman\{closure}(Object(support\Request))
#11 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\workerman\webman-framework\src\App.php(299): Webman\Cors\CORS->process(Object(support\Request), Object(Closure))
#12 D:\phpstudy_pro\WWW\2022\chenghu-yuanzhige-php\vendor\workerman\webman-framework\src\App.php(515): Webman\App::Webman\{closure}(Object(support\Request))`

**Comment by mouyong** [comment]
closed by #2

**Comment by mouyong** [comment]
Thanks.
